import { useEffect, useState } from "react";
import { onValue, ref } from "firebase/database";
import { database } from "./firebase";
import "./App.css";

function App() {
  const [drain, setDrain] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const drainRef = ref(database, "drains/drain1");

    const unsubscribe = onValue(
      drainRef,
      (snapshot) => {
        const data = snapshot.val();

        if (data) {
          setDrain(data);
          setError("");
        } else {
          setDrain(null);
          setError("No data found for Drain 1.");
        }

        setLoading(false);
      },
      (firebaseError) => {
        console.error(firebaseError);
        setError("Unable to connect to Firebase.");
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, []);

  const getStatusClass = (status) => {
    if (status === "GREEN") return "status-green";
    if (status === "YELLOW") return "status-yellow";
    if (status === "RED") return "status-red";
    return "status-unknown";
  };

  const formatTime = (timestamp) => {
    if (!timestamp) return "Unavailable";

    const date = new Date(Number(timestamp) * 1000);

    if (Number.isNaN(date.getTime())) {
      return "Invalid timestamp";
    }

    return date.toLocaleString();
  };

  if (loading) {
    return (
      <div className="app">
        <div className="loading-card">
          <div className="loader"></div>
          <h2>Connecting to Smart Drain Guard...</h2>
          <p>Reading live Firebase data.</p>
        </div>
      </div>
    );
  }

  if (error && !drain) {
    return (
      <div className="app">
        <div className="error-card">
          <div className="error-icon">!</div>
          <h2>Connection Error</h2>
          <p>{error}</p>
          <p className="small-text">
            Check the Firebase connection and database data.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="app">
      <header className="header">
        <div>
          <p className="eyebrow">REAL-TIME MONITORING SYSTEM</p>
          <h1>SMART DRAIN GUARD</h1>
          <p className="subtitle">
            Live drain blockage and water monitoring dashboard
          </p>
        </div>

        <div className="connection">
          <span className="connection-dot"></span>
          LIVE
        </div>
      </header>

      <main className="dashboard">
        <section className="drain-header">
          <div>
            <p className="label">MONITORING</p>
            <h2>DRAIN 1</h2>
          </div>

          <div
            className={`status-badge ${getStatusClass(
              drain?.status
            )}`}
          >
            {drain?.status || "UNKNOWN"}
          </div>
        </section>

        <section className="cards">
          <div className="card">
            <div className="card-icon">💧</div>
            <p className="card-label">BLOCKAGE</p>
            <h3>{drain?.blockage ?? "--"}%</h3>

            <div className="progress">
              <div
                className="progress-fill"
                style={{
                  width: `${Math.min(
                    Math.max(Number(drain?.blockage) || 0, 0),
                    100
                  )}%`,
                }}
              ></div>
            </div>
          </div>

          <div className="card">
            <div className="card-icon">🌊</div>
            <p className="card-label">WATER</p>
            <h3
              className={
                drain?.water_detected
                  ? "water-detected"
                  : "water-clear"
              }
            >
              {drain?.water_detected ? "DETECTED" : "NOT DETECTED"}
            </h3>
          </div>

          <div className="card">
            <div className="card-icon">⚠️</div>
            <p className="card-label">RISK SCORE</p>
            <h3>{drain?.risk_score ?? "--"}</h3>
            <p className="backend-label">Generated by backend</p>
          </div>
        </section>

        <section
          className={`risk-panel ${getStatusClass(
            drain?.status
          )}`}
        >
          <div>
            <p className="risk-label">CURRENT DRAIN STATUS</p>
            <h2>{drain?.status || "UNKNOWN"}</h2>
          </div>

          <div className="risk-score">
            {drain?.risk_score ?? "--"}
          </div>
        </section>

        <section className="updated-card">
          <div>
            <p className="card-label">LAST SENSOR UPDATE</p>
            <h3>{formatTime(drain?.time)}</h3>
          </div>

          <div className="realtime">
            ● REAL-TIME
          </div>
        </section>

        {error && (
          <div className="warning-message">
            {error}
          </div>
        )}
      </main>

      <footer>
        <p>
          Smart Drain Guard • Frontend monitoring dashboard
        </p>
        <p>
          Risk score and status are generated by the backend.
        </p>
      </footer>
    </div>
  );
}

export default App;